import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-gray-800 p-4">

          <ul className="flex space-x-4 max-w-4xl mx-auto">
            <li>
              <Link href="/" className="text-white hover:text-gray-300">
                Main Page
              </Link>
            </li>

            <li>
              <Link href="/cars" className="text-white hover:text-gray-300">
                Car List
              </Link>
            </li>
            
            <li>
              <Link href="/add" className="text-white hover:text-gray-300">
                Add Car
              </Link>
            </li>
          </ul>
          
        </nav>
        <main className="container mx-auto p-4 max-w-4xl">
          {children}
        </main>
      </body>
    </html>
  );
}

